server:
  port: 5001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    password: epiSode1
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update




