server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registeration
    username: root
    password: epiSode1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



